[package]
name = "advent2019"
version = "0.1.0"
authors = ["Max Veytsman <maxim@ontoillogical.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permutohedron = "0.2"
num = "0.2.0"
itertools = "0.8.2"